# config.yaml
# Example configuration for OTTAR: Cannon River
# A Wickert, 08 Jan 2024 & 15 Jun 2025

streamflow:
        # STREAMFLOW FILE: CSV expected
        # Possible column names:
        #   - Date or Timestamp
        #   - Discharge [m^3/s]
        # It may have other columns as long as it has these
        filename: Cannon_Q_1991onwards__including_Metric.csv
        datetime_column_name: Timestamp
        discharge_column_name: Discharge [m^3/s]
widthdata: 
        # CHANNEL-WIDTH DATA FILE (optional)
        # Possible column names:
        #   - Date
        #   - Width [m]
        filename: CannonWelch_Width_1991onwards.tsv
        datetime_column_name: Year
        width_column_name: Width [m]
        widtherror_column_name: SD [m]

# These parameters are updated based on the "doublemanning" manuscript
morphology:
        # Slope
        slope: 9E-4
        # Bank height [m]
        bank_height: 2.1
        # Initial width [m]
        initial_width: 40
        # Gary Parker's excess-stress ratio
        Parker_epsilon: 0.2

sediment:
        # Grain diameter [m]
        grain_diameter: 9.6E-3 # Calculated from n=0.025
        # Sediment density [kg/m^3]
        sediment_density: 2650
        
widening:
        # Threshold for entrainment of noncohesive sediment (Shields stress)
        critical_shields_stress_of_noncohesive_sediment: 0.0495
        # Threshold for erosion of cohesive material [Pa]
        critical_detachment_shear_stress_for_cohesive_sediement: 13
        # Noncohesive entrainment coefficient
        noncohesive_entrainment_coefficient__k_E: 1E-3
        # Cohesive detachment-rate coefficient
        coehsive_detachment_coefficient__k_d: 1E-6
        
narrowing:
        # Noncohesive trapping and holding efficiency coefficient
        trapping_and_holding_efficiency__k_n_noncohesive: 1E-2
        # Cohesive "stickiness" factor
        f_stickiness: 1E-2

doublemanning-flow:
        # These parameters are updated based on the "doublemanning" manuscript
        n_ch: 0.025 # [s / m^(1/3)]
        k_fp: 39.7 # [m$^(3-P_fp) / s]
        P_fp: 1.6666666666666666667
        stage_at_Q=0: 0.67 # [m]
        use_Rh: True # Use hydraulic radius (instead of just flow depth)

plotting:
        # True to show on screen, False to not
        show: True
        # If not empty, save to this filename; format guessed from extension
        # Currently, only one figure may be saved per run
        saveas: CannonWelch_Qb_fig.pdf 
        # Which kind of plots to generate? Boolean; blank defaults to false
        width: False
        discharge+width: True
        widening+narrowing+stress: False
        width+widening+narrowing+stress: False
        discharge+width+widening+narrowing+stress: 
        discharge+width+widening+narrowing+grain-stress-ratio:

output:
        # Save data to this file?
        # If it doesn't have the ".csv" extension, this will be appended
        output_csv_filename: 
        
