# config.yaml
# Example configuration for OTTAR: Green River
# A Wickert, 15 Jun 2025

streamflow:
        # STREAMFLOW FILE: CSV expected
        # Possible column names:
        #   - Date or Timestamp
        #   - Discharge [m^3/s]
        # It may have other columns as long as it has these
        filename: GreenRiver_atGreenRiver_Discharge__including_Metric.csv
        datetime_column_name: datetime
        discharge_column_name: GR Discharge [m^3/s]
widthdata: 
        # CHANNEL-WIDTH DATA FILE (optional)
        # Possible column names:
        #   - Date
        #   - Width [m]
        filename: GreenFortBottom_Width.tsv
        datetime_column_name: Year
        width_column_name: Width [m]
        widtherror_column_name: SD [m]

# These parameters are updated based on the "doublemanning" manuscript
morphology:
        # Slope
        slope: 2E-4
        # Bank height [m]
        bank_height: 2.3
        # Initial width [m]
        initial_width: 147.69
        # Gary Parker's excess-stress ratio
        Parker_epsilon: 0.2

sediment:
        # Grain diameter [m]
        grain_diameter: 0.3E-3 # Calculated from n=0.025
        # Sediment density [kg/m^3]
        sediment_density: 2650
        
widening:
        # Threshold for entrainment of noncohesive sediment (Shields stress)
        critical_shields_stress_of_noncohesive_sediment: 0.0495
        # Threshold for erosion of cohesive material [Pa]
        critical_detachment_shear_stress_for_cohesive_sediement: 3.01
        # Noncohesive entrainment coefficient
        noncohesive_entrainment_coefficient__k_E: 7.35E-5
        # Cohesive detachment-rate coefficient
        coehsive_detachment_coefficient__k_d: 0.872
        
narrowing:
        # Noncohesive trapping and holding efficiency coefficient
        trapping_and_holding_efficiency__k_n_noncohesive: 0.121
        # Cohesive "stickiness" factor
        f_stickiness: 0.00280

doublemanning-flow:
        # These parameters are updated based on the "doublemanning" manuscript
        n_ch: 0.024 # [s / m^(1/3)]
        k_fp: 26.4 # [m$^(3-P_fp) / s]
        P_fp: 1.94
        stage_at_Q=0: 0.67 # [m]
        use_Rh: True # Use hydraulic radius (instead of just flow depth)

plotting:
        # True to show on screen, False to not
        show: True
        # If not empty, save to this filename; format guessed from extension
        # Currently, only one figure may be saved per run
        saveas: 
        # Which kind of plots to generate? Boolean; blank defaults to false
        width: False
        discharge+width: True
        widening+narrowing+stress: False
        width+widening+narrowing+stress: False
        discharge+width+widening+narrowing+stress: 
        discharge+width+widening+narrowing+grain-stress-ratio:

output:
        # Save data to this file?
        # If it doesn't have the ".csv" extension, this will be appended
        output_csv_filename: 
        
